name: Deploy to neociteis

on:
  push:
    branches:
      - master

env:
  node-version: lts/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.node-version }}
    - run: npm i
    - run: npm run build
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v3
      with:
        api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        neocities_supporter: true
        preview_before_deploy: true
