name: Deploy to neociteis

on:
  push:
    branches:
      - master

env:
  node-version: lts/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.node-version }}
    - run: npm i
    - run: npm run build
    - name: Create deployment
      uses: bobheadxi/deployments@v0.6.1
      id: deployment
      with:
        step: start
        token: ${{ secrets.GITHUB_TOKEN }}
        env: neocities
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: false
    - name: Finish deployment
      uses: bobheadxi/deployments@v0.6.1
      if: always()
      with:
        step: finish
        token: ${{ secrets.GITHUB_TOKEN }}
        deployment_id: ${{ steps.deployment.outputs.deployment_id }}
        status: ${{ job.status }}
        env_url: https://gumcast.com
